### ISSUE TITLE
When property with default value is added set the default value

### ISSUE THREAD

**Issue by SlyNet** [joelabrahamsson/Page-Type-Builder#1]
Scenario:
Add new required property with default value to page type.
Expected result:
Existing pages have new property with default value set.
Actual result:
New property have empty value and throws an error.

**Comment by joelabrahamsson** [comment]
Hi!

It's interesting that it throws an exception. I'll look into this. Anyways, you probably need to specify DefaultValueType as well for it to work.

**Comment by SlyNet** [comment]
Yes, I'm specifying DefaultValueType also. The case when it happens is for example with PropertyNumber property type and Int32 as auto property.

**Comment by joelabrahamsson** [comment]
Could you send me the code for the property? Would be interesting to look at.

**Comment by SlyNet** [comment]
```
    [PageTypeProperty(SortOrder = 335,
        UniqueValuePerLanguage = true,
        Tab = typeof(RelatedContentTab),
        EditCaption = "Related content sort index",
        Type = typeof(PropertyNumber),
        Required = true,
        DefaultValue = 20,
        DefaultValueType = DefaultValueType.Value)]
    int RelatedContentSortIndex { get; set; }
```
